config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'welcome/index'

  devise_for :authors

  resources :authors, only: [:new, :create, :index, :show] do
    resources :journals, only: [:index, :new]
  end

  resources :journals do
    resources :entries, only: [:index, :new]
  end

  resources :entries, only: [:show, :update, :destroy, :edit, :new, :create] do
    resources :comments, only: [:new, :create, :index]
  end

  resources :comments, only: [:show, :update, :destroy, :edit]

  root 'welcome#index'

  get 'mydata', to: 'authors#my_data', format: :json

  devise_scope :author do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'signup', to: 'authors/registrations#new', as: :register
    get 'authors/edit', to: 'authors/registrations#edit', as: :edit
    put 'authors', to: 'authors/registrations#edit', as: :update
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visibility

  belongs_to :author
  belongs_to :entry
  enum visibility: { secret: 0, internal: 1, internet: 2 }

  validates :visibility, :inclusion => { :in => Proc.new {|comment| [comment.entry.visibility] } }
  validates_presence_of :entry, :author

  before_validation :ensure_visibility_matches_entry
  after_save :update_activity

  private
  def update_activity
    author.touch :active_at
  end

  def ensure_visibility_matches_entry
    self.visibility = entry.visibility
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_author!, only: [:edit, :update, :destroy, :new, :create]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.where(entry_id: params[:entry_id]).all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    unless @comment.view_permitted?(current_author)
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  # GET entries/1/comments/new
  def new
    unless current_author
      render(:file => File.join(Rails.root, 'public/401.html'), :status => 401, :layout => false)
    else
      entry = Entry.find(params[:entry_id])

      unless entry
        respond_to do |format|
          format.html { redirect_to root_url, alert: 'Can\'t write a comment for an entry that doesn\'t exist' , status: 303}
          format.json { head :unprocessable_entity }
        end
      else
        @comment = Comment.new(entry_id: entry.id, author_id: current_author.try(:id), body: params[:body] || 'I like this.')
      end
    end
  end

  # GET /comments/1/edit
  def edit
    unless current_author && @comment.author.id == current_author.try(:id)
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  # POST entries/1/comments
  # POST entries/1/comments.json
  def create
    unless current_author
      render(:file => File.join(Rails.root, 'public/401.html'), :status => 401, :layout => false)
      return false
    end

    entry = Entry.find(comment_params[:entry_id])

    unless entry
      respond_to do |format|
        format.html { redirect_to root_url, alert: 'Can\'t write a comment for an entry that doesn\'t exist' , status: 303}
        format.json { head :unprocessable_entity }
      end
      return false
    end

    @comment = Comment.new(
      comment_params.merge(author: current_author, visibility: entry.visibility, entry: entry)
    )

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.entry, notice: 'Comment was successfully saved.' , status: 303}
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    unless current_author && @comment.author_id == current_author.try(:id)
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return false
    end

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.entry, notice: 'Comment was successfully saved.' , status: 303}
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    unless current_author && @comment.author_id == current_author.try(:id)
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return false
    end
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully deleted.' , status: 303}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :entry_id, :visibility)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.author.name %></strong>
  <i>(<%= local_time_ago(comment.updated_at)%>)</i>
  <% if comment.author.id == current_author.try(:id) %>
  <span class="commentmenu">
    <%= link_to edit_comment_path(comment) do%>
      <i class="_plxs fa fa-pencil" aria-hidden="true"></i>
    <% end %>
    <%= link_to comment, data: {:confirm => 'Are you sure you wish to delete this comment?'}, :method => :delete do%>
      <i class="_plxs fa fa-trash" aria-hidden="true"></i>
    <% end %>
  </span>
  <% end %>
  <br/>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body, class: 'sr-only' %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <%= form.hidden_field :entry_id, :value => comment.entry_id %>
  <%= form.hidden_field :visibility, :value => comment.visibility %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h4>Commenting on "<%= link_to @comment.entry.title, @comment.entry %>"</h4>
<%= render 'form', comment: @comment %>
<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Body</th>
      <th>Entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author.name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.entry.title %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h4>Commenting on "<%= link_to @comment.entry.title, @comment.entry %>"</h4>

<%= render 'form', comment: @comment %>
<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<h4>Comment on "<%= link_to @comment.entry.title, @comment.entry %>"</h4>
<%= render partial: 'comment', object: @comment %>
<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>