config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'welcome/index'

  devise_for :authors

  resources :authors, only: [:new, :create, :index, :show] do
    resources :journals, only: [:index, :new]
  end

  resources :journals do
    resources :entries, only: [:index, :new]
  end

  resources :entries, only: [:show, :update, :destroy, :edit, :new, :create] do
    resources :comments, only: [:new, :create, :index]
  end

  resources :comments, only: [:show, :update, :destroy, :edit]

  root 'welcome#index'

  get 'mydata', to: 'authors#my_data', format: :json

  devise_scope :author do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'signup', to: 'authors/registrations#new', as: :register
    get 'authors/edit', to: 'authors/registrations#edit', as: :edit
    put 'authors', to: 'authors/registrations#edit', as: :update
  end
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :journals, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :entries, through: :journals, dependent: :destroy

  after_create :create_drafts_journal
  before_destroy Proc.new {|a| a.draft_journal.try(:destroy)}

  def draft_journal
    journals.where(locked: true).first
  end

  private
  def create_drafts_journal
    journals.create(visibility: 'secret', title: 'Drafts', locked: true)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!, only: [:edit, :update, :destroy]
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
    unless current_author && current_author == @author
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    unless current_author && current_author == @author
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return false
    end
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, status: 303, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def my_data
    unless current_author
      render(:file => File.join(Rails.root, 'public/401.html'), :status => 401, :layout => false)
      return false
    end

    data = {
      account: current_author.attributes.slice('name', 'bio', 'created_at', 'active_at', 'email'),
      journals: current_author.journals.map { |j| { j.title.to_sym => j.attributes, entries: j.entries.map(&:attributes) } },
      comments: current_author.comments.all.map(&:attributes)
    }

    filename = "#{current_author.name}.json"
    temp_file = Tempfile.new()
    File.open(temp_file, 'w+') do |f|
      f << JSON.pretty_generate(data)
    end

    send_file(temp_file, filename: filename, type: :json)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<%= link_to author do %>
  <h2 class="_c-red-dark"><%= author.name %></h2>
<% end %>
<div container>
  <%= simple_format(author.bio.truncate(140)) %>
</div>
<br/>

app/views/authors/_author_small.html.erb
<%= link_to author_small do %>
  <h4 class="_c-red-dark"><%= author_small.name %></h4>
<% end %>
<br/>

app/views/authors/_changepassword.html.erb
<%= form_with(model: author, local: true, class: 'form-signin') do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
  <%= form.label :password, :class => 'sr-only' %><br />
  <%= form.password_field :password, :class => 'form-control', :placeholder => 'password' %>
</div>
<div class="field">
  <%= form.label :password_confirmation, :class => 'sr-only' %><br />
  <%= form.password_field :password_confirmation, :class => 'form-control', :id => 'inputPassword', :placeholder => 'password_confirmation' %>
</div>
<div class="actions">
  <%= form.submit "Sign Up", :class => 'btn btn-lg btn-primary btn-block' %>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true, class: 'form-signin') do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name, :class => 'sr-only' %><br />
    <%= form.text_field :name, :class => 'form-control', :id => 'inputName', :placeholder => 'name' %>
  </div>
  <div class="field">
    <%= form.label :email, :class => 'sr-only' %><br />
    <%= form.text_field :email, :class => 'form-control', :id => 'inputEmail', :placeholder => 'email' %>
  </div>

  <div class="field">
    <%= form.label :bio, :class => 'sr-only' %><br />
    <%= form.text_area :bio, :class => 'form-control', :id => 'inputBio'%>
  </div>
  <div class="actions">
    <%= form.submit "Sign Up", :class => 'btn btn-lg btn-primary btn-block' %>
  </div>
<% end %>

app/views/authors/index.html.erb
<h1>All Authors</h1>
<%= render partial: 'author', collection: @authors %>

app/views/authors/new.html.erb
<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="_inline-block"><%= @author.name %></h1>
<% if current_author == @author %>
  <%= link_to edit_author_registration_url, class: "_pls" do%>
  <i class="_plxs fa fa-pencil" aria-hidden="true">
    <span>&nbsp;Edit</span>
  </i>
  <%end%>
  <br/>
  <a href="/mydata">Download all my Data (.json)</a>
<% end %>
<article container>
  <%= simple_format(@author.bio) %>
</article>

<% collection = @author.journals.allowed(current_author) %>
<% if collection.count > 0 %>
  <h2 class="_inline"><%= @author.name.possessive %> <%=collection.count > 1 ? "Journals":"Journal" %></h2>
  <% if @author == current_author%>
    <%= link_to new_journal_path do %>
      <span class="_prxs _pls">New&nbsp;Journal&nbsp;<i class="fa fa-plus" aria-hidden="true"></i></span>
    <% end %>
  <% end %>
  <%= render partial: 'journals/journal', collection: collection %>
<% else %>
  <h3><%= @author.name.split.first%> doesn't have any journals you're allowed to see.</h3>
<% end %>

<br/>