config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'welcome/index'

  devise_for :authors

  resources :authors, only: [:new, :create, :index, :show] do
    resources :journals, only: [:index, :new]
  end

  resources :journals do
    resources :entries, only: [:index, :new]
  end

  resources :entries, only: [:show, :update, :destroy, :edit, :new, :create] do
    resources :comments, only: [:new, :create, :index]
  end

  resources :comments, only: [:show, :update, :destroy, :edit]

  root 'welcome#index'

  get 'mydata', to: 'authors#my_data', format: :json

  devise_scope :author do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'signup', to: 'authors/registrations#new', as: :register
    get 'authors/edit', to: 'authors/registrations#edit', as: :edit
    put 'authors', to: 'authors/registrations#edit', as: :update
  end
end

app/models/journal.rb
class Journal < ApplicationRecord
  include Visibility

  enum visibility: { secret: 0, internal: 1, internet: 2 }

  belongs_to :author
  has_many :entries, dependent: :destroy
  has_many :comments, through: :entries

  before_save :ensure_entries_share_visibility

  def title
    return attributes['title'].blank? ? 'Untitled' : attributes['title']
  end

  private

  def ensure_entries_share_visibility
    entries.update_all(visibility: visibility)
    comments.update_all(visibility: visibility)
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :authenticate_author!, only: [:edit, :update, :destroy]
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.allowed(current_author).all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
    unless @journal.view_permitted?(current_author)
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  # GET /journals/new
  def new
    unless current_author
      render(:file => File.join(Rails.root, 'public/401.html'), :status => 401, :layout => false)
    else
      @journal = Journal.new(author: current_author, title: "My Newest Journal")
    end
  end

  # GET /journals/1/edit
  def edit
    unless current_author && @journal.author_id == current_author.try(:id)
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  # POST /journals
  # POST /journals.json
  def create
    unless current_author
      render(:file => File.join(Rails.root, 'public/401.html'), :status => 401, :layout => false)
      return false
    end

    @journal = Journal.new(journal_params)
    @journal.author_id = current_author.try(:id)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.', status: 303 }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    unless current_author && @journal.author_id == current_author.try(:id)
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return false
    end
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.', status: 303 }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    unless current_author && @journal.author_id == current_author.try(:id)
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return false
    end
    if @journal.locked == true
      respond_to do |format|
        format.html { redirect_to current_author, alert: 'Cannot destroy drafts journal', status: 303 }
        format.json { head :unprocessable_entity }
      end
      return false
    end
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to current_author, notice: 'Journal was successfully deleted.', status: 303 }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:title, :visibility)
    end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_with(model: journal, local: true) do |form| %>
  <% if journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% journal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1 class="title-label">Title:&nbsp;</h1>
  <%= form.text_field :title, class: "title-input" %>
  <br/>
  <br/>
  <h1 class="inline-form">Visibility:&nbsp;</h1>
  <div grid>
    <div class="radio-div" column>
      <%=form.radio_button :visibility, "secret", id: "journal_secret", name:"journal[visibility]"%>
      <label for="journal_secret">
        <h4>Secret&nbsp;<i class="fa fa-lock" aria-hidden="true" title="This journal is private. Only you can see it."></i></h4>
        <p>Like your childhood diary! No one but you is allowed to see this.</p>
      </label>
    </div>
    <div class="radio-div" column>
      <%=form.radio_button :visibility, "internal", id: "journal_internal", name:"journal[visibility]"%>
      <label for="journal_internal">
        <h4>Internal</h4>
        <p> For members of Reflection Pad only.  They'll be able to view and comment on this.</p>
      </label>
    </div>
    <div class="radio-div" column>
      <%=form.radio_button :visibility, "internet", id: "journal_internet", name:"journal[visibility]"%>
      <label for="journal_internet">
        <h4>Internet&nbsp;<i class="fa fa-globe" aria-hidden="true" title="This journal is public. The entire internet can see it."></i></h4>
        <p> Publicly hosted on the internet.  Only members can comment. </p>
      </label>
    </div>
  </div>
  <div class="actions _pts">
    <%= form.submit %>
  </div>
<% end %>

app/views/journals/_journal.html.erb
<h3><%= render partial: 'journals/journal_title', object: journal %></h3>
<% collection = journal.entries.order(:created_at).limit(3)%>
<% if !collection.empty? %>
<%= render partial: 'entries/entry', collection: collection %>
<% else %>
<h4>It looks like this journal has no entries yet...
    <%= journal.author_id == current_author.try(:id) ? link_to("Why not write one?", new_journal_entry_url(journal)) : ""%></h4>
<% end %>

app/views/journals/_journal_card.html.erb
<% journal = journal_card %>
<div class="card-box">
  <div class="header">
    <h3 class="title"><%= render partial: 'journals/journal_title', object: journal %></h3>
  </div>
  <div class="card-content">
    <p class="content">
      <% collection = journal.entries.order(:created_at).limit(2)%>
      <% if !collection.empty? %>
      <%= render partial: 'entries/entry', collection: collection %>
      <% else %>
      <h4>It looks like this journal has no entries yet...</h4>
      <% end %>
    </p>
  </div>
  <div class="footer">
    <strong>Author: <%= link_to journal.author.name, journal.author %></strong>
  </div>
</div>

app/views/journals/_journal_title.html.erb
<% journal = journal_title %>
<%= link_to journal.title, journal %>
<% if journal.secret? %>
<i class="fa fa-lock" aria-hidden="true" title="This journal is private. Only you can see it."></i>
<% elsif journal.internet? %>
<i class="fa fa-globe" aria-hidden="true" title="This journal is public. The entire internet can see it."></i>
<% end %>

app/views/journals/edit.html.erb
<%= render 'form', journal: @journal %>
<%= link_to 'Back', @journal.author %>

app/views/journals/index.html.erb
<h1>Journals</h1>

<table>
  <thead>
    <tr>
      <th>Journal Title</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journals.each do |journal| %>
      <tr>
        <td><%= journal.title %></td>
        <td><%= journal.author.name %></td>
        <td><%= link_to 'Show', journal %></td>
        <td><%= link_to 'Edit', edit_journal_path(journal) %></td>
        <td><%= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr><td colspan="5"><pre><%= journal.attributes%></pre></td></tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/journals/new.html.erb
<%= render 'form', journal: @journal %>

app/views/journals/show.html.erb
<h1><%= render partial: 'journals/journal_title', object: @journal %></h1>
<% if @journal.author_id == current_author.try(:id) %>
<span class="entrymenu">
  <%= link_to edit_journal_path(@journal) do%>
    <i class="_pls fa fa-pencil" aria-hidden="true">
      <span>&nbsp;Edit&nbsp;Journal&nbsp;Settings</span>
    </i>
  <% end %>
  <%= link_to @journal, data: {:confirm => 'Are you sure you want to delete this journal and all of its entries?'}, :method => :delete do%>
    <i class="_pls fa fa-trash" aria-hidden="true">
      <span>&nbsp;Delete</span>
    </i>
  <% end %>
</span>
<% end %>
<% collection = @journal.entries.order(:created_at) %>
<% if !collection.empty? %>
<%= render partial: 'entries/entry', collection: collection %>
<% else %>
<h4>It looks like this journal has no entries yet...
    <%=@journal.author_id == current_author.try(:id) ? link_to("Why not write one?", new_journal_entry_url(@journal)) : ""%></h4>
<% end %>