config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'welcome/index'

  devise_for :authors

  resources :authors, only: [:new, :create, :index, :show] do
    resources :journals, only: [:index, :new]
  end

  resources :journals do
    resources :entries, only: [:index, :new]
  end

  resources :entries, only: [:show, :update, :destroy, :edit, :new, :create] do
    resources :comments, only: [:new, :create, :index]
  end

  resources :comments, only: [:show, :update, :destroy, :edit]

  root 'welcome#index'

  get 'mydata', to: 'authors#my_data', format: :json

  devise_scope :author do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'signup', to: 'authors/registrations#new', as: :register
    get 'authors/edit', to: 'authors/registrations#edit', as: :edit
    put 'authors', to: 'authors/registrations#edit', as: :update
  end
end

app/views/layouts/_topnav.html.erb
<nav id="topnav" grid="justify-center">
  <ul grid="justify-center">
    <li column>
      <a href="<%= root_path %>" title="Explore">
        <i class="fa fa-2x fa-compass" aria-hidden="true">
          <span class="_pls">&nbsp;Explore</span>
        </i>
      </a>
    </li>
    <% if author_signed_in? %>
    <li column>
      <a href="<%= author_path(current_author) %>" title="My Journals">
        <i class="fa fa-2x fa-book" aria-hidden="true">
          <span class="_pls">&nbsp;My&nbsp;Journals</span>
        </i>
      </a>
    </li>
    <li column>
      <a href="<%= new_entry_path %>" title="New Entry">
        <i class="fa fa-2x fa-pencil" aria-hidden="true">
          <span class="_pls">&nbsp;New&nbsp;Entry</span>
        </i>
      </a>
    </li>
    <li column>
      <a data-method="delete" href="<%= destroy_author_session_path %>">
        <i class="fa fa-2x fa-sign-out" aria-hidden="true">
          <span class="_pls">&nbsp;Log&nbsp;out</span>
        </i>
      </a>
    </li>
    <% else %>
    <li column>
      <a href="<%= new_registration_path(Author) %>">
        <i class="fa fa-2x fa-user-plus" aria-hidden="true">
          <span class="_pls">Sign&nbsp;up</span>
        </i>
      </a>
    </li>
    <li column>
      <a href="<%= new_author_session_path %>">
        <i class="fa fa-2x fa-sign-in" aria-hidden="true">
          <span class="_pls">&nbsp;Log&nbsp;in</span>
        </i>
      </a>
    </li>
    <% end %>
  </ul>
  <a id="menutoggle">
    <i class="fa fa-bars fa-2x _plxs" aria-hidden="true">&nbsp;
      <span class="_pls">&nbsp;Menu</span>
    </i>
  </a>
</br>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReflectionPad</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'layouts/topnav' %>
    <main container="small" class="<%= controller_name %> <%= action_name %>">
      <div id="notice-area">
        <% if notice %>
        <section class="alert-box -success">
          <p><%= notice %></p>
          <a class="close" href="#">×</a>
        </section>
        <% end %>
        <% if alert %>
        <section class="alert-box -danger">
          <p><%= alert %></p>
          <a class="close" href="#">×</a>
        </section>
        <% end %>
      </div>

      <%= yield %>
    </main>
  </body>
</html>